id: P006861
initial_creation_type: ocr
source_metadata:
  id: bdr:W2GS1315
  title: ཁྲི་ཆེན་བློ་བཟང་དགེ་ལེགས་དཔལ་བཟང་པོའི་རྣམ་པར་ཐར་པ་དད་པའི་པད་མོའི་འཛུམ་བྱེད་ངོ་མཚར་ཉིན་བྱེད་གསར་པའི་སྣང་བ།
  author: ''
  volumes: {}
