id: P006861
initial_creation_type: ocr
source_metadata:
  id: bdr:W2GS1315
  title: ཁྲི་ཆེན་བློ་བཟང་དགེ་ལེགས་དཔལ་བཟང་པོའི་རྣམ་པར་ཐར་པ་དད་པའི་པད་མོའི་འཛུམ་བྱེད་ངོ་མཚར་ཉིན་བྱེད་གསར་པའི་སྣང་བ།
  author: ''
  volumes:
    4769a3598efb4a6286bef79ffd162f5b:
      image_group_id: I1KG6104
      title: ''
      volume_number: 1
      total_pages: 40
